### ISSUE TITLE
Collaborate with @serokell

### ISSUE THREAD

**Issue by chshersh** [TerrorJack/direct-rocksdb#1]
Do you know that there exist haskell bindings to `RocksDB` which are maintained by @serokell team and used in `cardano-sl` project?

* https://github.com/serokell/rocksdb-haskell

Maybe instead of creating new package you can help developing existing one? Or you're following different goals?

**Comment by TerrorJack** [comment]
@ChShersh The original goal of this package is "a smoother build experience" since it builds RocksDB in place, so it can stick to a newer version and works well on distros without RocksDB in package repos. The other reason is simply fun.

I have to admit this is a side project and I haven't got too much time to implement more functionality (other than basic K/V store and complete raw bindings). I'm of course willing to help with @serokell 's bindings. In fact I'm in the middle of your interview, looking forward to receiving the tech challenge and passing it so I can definitely collaborate, lol.

**Comment by chshersh** [comment]
@TerrorJack Wow, great news! I just discovered your project on Stackage and was interested in your opinion regarding it :slightly_smiling_face:
